version: '2.3'

services:

    app:
        build: .
        container_name: app
        volumes: 
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy
        networks: 
            - app-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        ports: 
            - "8000:80" 
        restart: always
        tty: true
        volumes: 
            - .:/var/www
        networks: 
            - app-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 4
        volumes: 
            - ./.docker/dbdata:/var/lib/mysql
        networks: 
            - app-network

    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge
        