apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        # resources:
        #   requests:
        #     cpu: "200m"
        #     memory: "100Mi"
        #   limits:
        #     cpu: "250m"

        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf  
          readOnly: true
          
      
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf